#cloud-config

# Run commands
# Install security updates on Centos from IBM Cloud private mirror (no public access)
# Update and restart server firewall
# Install http server and php
# Create info page for testing
# Change listening port fot http to 8080
# Enable service start upon reboot
# Start http server

runcmd:
  - [ yum, --security, update ]
  - [ firewall-offline-cmd, --add-port, 8080/tcp ]
  - [ systemctl, stop, firewalld ]
  - [ systemctl, start, firewalld ]
  - [ yum, install, -y, httpd, php, php-mysqlnd ]
  - [ sed, -i, "s/80/8080/g", /etc/httpd/conf/httpd.conf ]
  - [ systemctl, enable, httpd.service ]
  - [ systemctl, start, httpd.service ]

write_files:
  - path: /var/www/html/info.php
    content: |
         <?php
          phpinfo(); 
         ?>
